ezpublish:
    system:
        site_group:
            content_view:
                full:
                    homepage:
                        template: "@ezdesign/content/full/homepage.html.twig"
                        controller: "WetrailAppBundle:ContentViewController/Homepage:full"
                        match:
                            Identifier\ContentType:
                                - homepage
                    camping_list:
                        template: "@ezdesign/content/full/rubric_list.html.twig"
                        controller: "WetrailAppBundle:ContentViewController/RubricList:full"
                        match:
                            Identifier\ContentType:
                                - rubric_trails
                                - rubric_course
                                - rubric_equipment
                                - rubric_nutrition
                    file:
                        template: null
                        controller: WetrailAppBundle:ContentViewController\File:download
                        match:
                            Identifier\ContentType:
                            - file
                    default:
                        template: "@ezdesign/errors/404.html.twig"
                        controller: "WetrailAppBundle:Default:index"
                        match: ~